image: Visual Studio 2026

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

init:
  - ps: |
      Get-Service -Name 'MSSQL*' |
        Format-Table Name, Status

      Start-Service 'MSSQL$SQL2022'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build -c Release --no-restore

test_script:
  - dotnet test -c Release --no-restore --no-build